[project]
authors = ["Amy Van Scoyoc <avanscoyoc@berkeley.edu>"]
channels = ["conda-forge"]
description = "A comparison of machine learning model performance on non-avian audio"
name = "bird_new"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10"
libgl = "*"
glib = "*"
ipykernel = ">=6.29.5,<7"
jupyterlab = ">=4.3.5,<5"
jupyter = ">=1.1.1,<2"

[pypi-dependencies] 
tensorflow_hub = "*"
opensoundscape = ">=0.11.0"
torch = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
timm = "*"
torchaudio = "*"
tensorflow = "*"
scikit-learn = "*"
