[project]
authors = ["Amy Van Scoyoc <avanscoyoc@berkeley.edu>"]
channels = ["conda-forge"]
description = "A comparison of machine learning model performance on non-avian audio"
name = "bird_new"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10"
numpy = "*"
pandas = "*"
pytorch = "*"
tqdm = "*"
timm = "*"
torchaudio = "*"
tensorflow = "*"

[pypi-dependencies]
opensoundscape = "*"
tensorflow_hub = "*"
