[project]
authors = ["Amy Van Scoyoc <avanscoyoc@berkeley.edu>"]
channels = ["conda-forge"]
description = "A comparison of machine learning model performance on non-avian audio"
name = "bird_new"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10"
numpy = "*"
pandas = "*"
pytorch = "*"
tqdm = "*"
timm = "*"
torchaudio = "*"
tensorflow = "*"
pip = ">=25.0.1,<26"
scikit-learn = ">=1.6.1,<2"
libgl = ">=1.7.0,<2"
glib = ">=2.82.2,<3"

[pypi-dependencies] 
tensorflow_hub = "*"
opensoundscape = "*"