[project]
authors = ["Amy Van Scoyoc <avanscoyoc@berkeley.edu>"]
channels = ["conda-forge"]
description = "A comparison of machine learning model performance on non-avian audio"
name = "bird_new"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "1.26.4"
pandas = "2.2.3"
torch = "2.5.1"
tqdm = "4.67.1"
opensoundscape = "0.11.0"
timm = "1.0.13"
torchaudio = "2.5.1"
tensorflow_hub = "0.14.0
tensorflow = "2.14.0"